USE [EmployeeSeatDB]
GO

CREATE PROCEDURE SP_CHANGE_SEAT
    @EMP_ID VARCHAR(5),
    @NEW_SEAT_SEQ INT
AS
BEGIN
    SET NOCOUNT ON;
    BEGIN TRANSACTION;

    IF NOT EXISTS (SELECT 1 FROM EMPLOYEE WHERE EMP_ID = @EMP_ID)
    BEGIN
        ROLLBACK TRANSACTION;
        THROW 50001, 'Employee not found', 1;
    END

    IF NOT EXISTS (SELECT 1 FROM SEATING_CHART WHERE FLOOR_SEAT_SEQ = @NEW_SEAT_SEQ)
    BEGIN
        ROLLBACK TRANSACTION;
        THROW 50002, 'Seat not found', 1;
    END

    IF EXISTS (SELECT 1 FROM EMPLOYEE WHERE FLOOR_SEAT_SEQ = @NEW_SEAT_SEQ AND EMP_ID <> @EMP_ID)
    BEGIN
        ROLLBACK TRANSACTION;
        THROW 50003, 'Seat already occupied', 1;
    END

    DECLARE @OLD_SEAT_SEQ INT;
    SELECT @OLD_SEAT_SEQ = FLOOR_SEAT_SEQ FROM EMPLOYEE WHERE EMP_ID = @EMP_ID;

    UPDATE EMPLOYEE
       SET FLOOR_SEAT_SEQ = @NEW_SEAT_SEQ
     WHERE EMP_ID = @EMP_ID;

    INSERT INTO SEAT_CHANGE_LOG(EMP_ID, OLD_SEAT_SEQ, NEW_SEAT_SEQ)
    VALUES(@EMP_ID, @OLD_SEAT_SEQ, @NEW_SEAT_SEQ);

    COMMIT TRANSACTION;
END;
