spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=EmployeeSeatDB;encrypt=false;trustServerCertificate=true
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.sql.init.mode=never
server.port=8080